source "https://rubygems.org"

ruby "2.4.6"

#gem "coffee-rails", "~> 4.1.0"
gem "jquery-rails"
gem "rails", ">= 5"
gem "sass-rails", "~> 5.0"
gem "sqlite3"
gem "turbolinks"
gem "uglifier", ">= 1.3.0"
gem "active_model_serializers", "~> 0.8.0"
gem 'record_tag_helper', '~> 1.0'

group :development do
  gem "web-console", "~> 2.0"
end

group :development, :test do
  gem "byebug"
  gem "factory_bot_rails"
  gem "rspec-rails", "~> 3.0"
  gem "shoulda-matchers"
  gem "spring"
end

group :test do
  gem "capybara"
  gem "database_cleaner"
  gem "email_spec"
  gem 'rails-controller-testing'
end
