source "https://rubygems.org"

gem "coffee-rails", "~> 4.1.0"
gem "jquery-rails"
gem "rails", "4.2.1"
gem "sass-rails", "~> 5.0"
gem "sqlite3"
gem "turbolinks"
gem "uglifier", ">= 1.3.0"

group :development, :test do
  gem "byebug"
  gem "capybara"
  gem "database_cleaner"
  gem "factory_girl_rails"
  gem "rspec-rails", "~> 3.0"
  gem "shoulda-matchers"
  gem "spring"
  gem "web-console", "~> 2.0"
end
